//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindMyHome.Domain.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FindMyHome.Domain.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Booli API returned an error..
        /// </summary>
        public static string BooliApiErrorEng {
            get {
                return ResourceManager.GetString("BooliApiErrorEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det går i nuläget inte att hämta annonser från Booli..
        /// </summary>
        public static string BooliApiErrorSwe {
            get {
                return ResourceManager.GetString("BooliApiErrorSwe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bekräfta nytt lösenord.
        /// </summary>
        public static string ConfirmNewPasswordInputSwe {
            get {
                return ResourceManager.GetString("ConfirmNewPasswordInputSwe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bekräfta lösenord.
        /// </summary>
        public static string ConfirmPasswordInputSwe {
            get {
                return ResourceManager.GetString("ConfirmPasswordInputSwe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuvarande lösenord.
        /// </summary>
        public static string CurrentPasswordInputSwe {
            get {
                return ResourceManager.GetString("CurrentPasswordInputSwe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Foursquare API returned an error..
        /// </summary>
        public static string FoursquareApiErrorEng {
            get {
                return ResourceManager.GetString("FoursquareApiErrorEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det går i nuläget inte att hämta platser från Foursquare..
        /// </summary>
        public static string FoursquareApiErrorSwe {
            get {
                return ResourceManager.GetString("FoursquareApiErrorSwe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Något gick fel vid kommunikation med extern datakälla..
        /// </summary>
        public static string GenericApiBadReqSwe {
            get {
                return ResourceManager.GetString("GenericApiBadReqSwe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ditt {0} måste vara minst {2} tecken långt..
        /// </summary>
        public static string InputLengthErrorSwe {
            get {
                return ResourceManager.GetString("InputLengthErrorSwe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ej giltiga platser angavs..
        /// </summary>
        public static string InvalidFoursquareCategoiresDescSwe {
            get {
                return ResourceManager.GetString("InvalidFoursquareCategoiresDescSwe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plats sök.
        /// </summary>
        public static string InvalidFoursquareCategoiresHeadSwe {
            get {
                return ResourceManager.GetString("InvalidFoursquareCategoiresHeadSwe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nytt lösenord.
        /// </summary>
        public static string NewPasswordInputSwe {
            get {
                return ResourceManager.GetString("NewPasswordInputSwe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det nya lösenordet och bekräftelsen matchar inte..
        /// </summary>
        public static string PasswordDontMatchSwe {
            get {
                return ResourceManager.GetString("PasswordDontMatchSwe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lösenord.
        /// </summary>
        public static string PasswordInputSwe {
            get {
                return ResourceManager.GetString("PasswordInputSwe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lösenorden matchar inte..
        /// </summary>
        public static string PasswordsDontMatchSwe {
            get {
                return ResourceManager.GetString("PasswordsDontMatchSwe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det nya lösenordet måste vara minst {2} tecken långt..
        /// </summary>
        public static string PasswordToShortSwe {
            get {
                return ResourceManager.GetString("PasswordToShortSwe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kom ihåg mig?.
        /// </summary>
        public static string RememberMeInputSwe {
            get {
                return ResourceManager.GetString("RememberMeInputSwe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} måste anges..
        /// </summary>
        public static string RequiredInputSwe {
            get {
                return ResourceManager.GetString("RequiredInputSwe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Användarnamn.
        /// </summary>
        public static string UsernameInputSwe {
            get {
                return ResourceManager.GetString("UsernameInputSwe", resourceCulture);
            }
        }
    }
}
