//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindMyHome.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FindMyHome.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authentication provider returned an error. Please verify your entry and try again. If the problem persists, please contact your system administrator..
        /// </summary>
        public static string AuthProviderErrorEng {
            get {
                return ResourceManager.GetString("AuthProviderErrorEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autentiseringenstjänsten returnerade ett fel. Var vänligen och kontrollera fälten och försök igen. Om felet kvarstår, vänligen kontakta systemadministratören..
        /// </summary>
        public static string AuthProviderErrorSwe {
            get {
                return ResourceManager.GetString("AuthProviderErrorSwe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Den externa tjänsten har tagits bort..
        /// </summary>
        public static string ExternalProviderRemovedSuccessSwe {
            get {
                return ResourceManager.GetString("ExternalProviderRemovedSuccessSwe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det angivna användarnamnet och/eller lösenordet är fel..
        /// </summary>
        public static string IncorrectUserNameOrPasswordSwe {
            get {
                return ResourceManager.GetString("IncorrectUserNameOrPasswordSwe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal server error occured..
        /// </summary>
        public static string InternalServerErrorEng {
            get {
                return ResourceManager.GetString("InternalServerErrorEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett internt serverfel uppstod..
        /// </summary>
        public static string InternalServerErrorSwe {
            get {
                return ResourceManager.GetString("InternalServerErrorSwe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit måste vara mellan 1 och 30..
        /// </summary>
        public static string LimitLengthSwe {
            get {
                return ResourceManager.GetString("LimitLengthSwe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max pris måste vara mellan 0 och 2147483647..
        /// </summary>
        public static string MaxPriceSwe {
            get {
                return ResourceManager.GetString("MaxPriceSwe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max hyra måsta vara mellan 0 och 2147483647..
        /// </summary>
        public static string MaxRentSwe {
            get {
                return ResourceManager.GetString("MaxRentSwe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objekttyperna måste vara mellan 2 och 70..
        /// </summary>
        public static string ObjectTypesLengthSwe {
            get {
                return ResourceManager.GetString("ObjectTypesLengthSwe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objekttyperna måste innehålla giltiga värden..
        /// </summary>
        public static string ObjectTypesValueSwe {
            get {
                return ResourceManager.GetString("ObjectTypesValueSwe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset måste vara mellan 0 och 2147483647..
        /// </summary>
        public static string OffsetLengthSwe {
            get {
                return ResourceManager.GetString("OffsetLengthSwe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ditt lösenord har ändrats..
        /// </summary>
        public static string PasswordChangeSuccessSwe {
            get {
                return ResourceManager.GetString("PasswordChangeSuccessSwe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det nuvarande lösenordet är fel eller är det nya lösenordet inte giltigt..
        /// </summary>
        public static string PasswordFailureSwe {
            get {
                return ResourceManager.GetString("PasswordFailureSwe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password provided is invalid. Please enter a valid password value..
        /// </summary>
        public static string PasswordInvalidEng {
            get {
                return ResourceManager.GetString("PasswordInvalidEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det angivna lösenordet är inte giltig. Vänligen ange ett giltigt lösenord..
        /// </summary>
        public static string PasswordInvalidSwe {
            get {
                return ResourceManager.GetString("PasswordInvalidSwe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ditt lösenord är sparat..
        /// </summary>
        public static string PasswordSetSuccessSwe {
            get {
                return ResourceManager.GetString("PasswordSetSuccessSwe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The search term must be 1-100 characters..
        /// </summary>
        public static string SearchTermLengthEng {
            get {
                return ResourceManager.GetString("SearchTermLengthEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Söktermen måste vara mellan 1 och 100 tecken..
        /// </summary>
        public static string SearchTermLengthSwe {
            get {
                return ResourceManager.GetString("SearchTermLengthSwe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A search term is required..
        /// </summary>
        public static string SearchTermRequiredEng {
            get {
                return ResourceManager.GetString("SearchTermRequiredEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En sökterm måste anges..
        /// </summary>
        public static string SearchTermRequiredSwe {
            get {
                return ResourceManager.GetString("SearchTermRequiredSwe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred. Please verify your entry and try again. If the problem persists, please contact your system administrator..
        /// </summary>
        public static string UnknownErrorEng {
            get {
                return ResourceManager.GetString("UnknownErrorEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En oväntat fel uppstod. Var vänligen och kontrollera fälten och försök igen. Om felet kvarstår, vänligen kontakta systemadministratören..
        /// </summary>
        public static string UnknownErrorSwe {
            get {
                return ResourceManager.GetString("UnknownErrorSwe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user creation request has been canceled. Please verify your entry and try again. If the problem persists, please contact your system administrator..
        /// </summary>
        public static string UserCreateReqErrorEng {
            get {
                return ResourceManager.GetString("UserCreateReqErrorEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skapandet av användare har avbrutits. Var vänligen och kontrollera fälten och försök igen. Om felet kvarstår, vänligen kontakta systemadministratören..
        /// </summary>
        public static string UserCreateReqErrorSwe {
            get {
                return ResourceManager.GetString("UserCreateReqErrorSwe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name already exists. Please enter a different user name..
        /// </summary>
        public static string UsernameAlreadyExistsEng {
            get {
                return ResourceManager.GetString("UsernameAlreadyExistsEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett användarnamn med det namnet finns redan. Vänligen ange ett nytt användarnamn..
        /// </summary>
        public static string UsernameAlreadyExistsSwe {
            get {
                return ResourceManager.GetString("UsernameAlreadyExistsSwe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name provided is invalid. Please check the value and try again..
        /// </summary>
        public static string UsernameInvalidEng {
            get {
                return ResourceManager.GetString("UsernameInvalidEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det angivna användarnamnet är inte giltigt. Kontrollera värdet och försök igen..
        /// </summary>
        public static string UsernameInvalidSwe {
            get {
                return ResourceManager.GetString("UsernameInvalidSwe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Går inte att skapa ett lokalt konto. Ett konto med namnet \&quot;{0}\&quot; kanske redan finns..
        /// </summary>
        public static string UsernameMayAlreadyExistsSwe {
            get {
                return ResourceManager.GetString("UsernameMayAlreadyExistsSwe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venues måste vara minst 2 tecken..
        /// </summary>
        public static string VenuesLengthSwe {
            get {
                return ResourceManager.GetString("VenuesLengthSwe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Söktermen måste vara minst 2 tecken..
        /// </summary>
        public static string VenueTermLengthSwe {
            get {
                return ResourceManager.GetString("VenueTermLengthSwe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En sökterm måste anges..
        /// </summary>
        public static string VenueTermRequiredSwe {
            get {
                return ResourceManager.GetString("VenueTermRequiredSwe", resourceCulture);
            }
        }
    }
}
